# Generated by Django 5.0.6 on 2024-06-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='idproduct',
            field=models.CharField(default=1, max_length=100, verbose_name='Codigo del producto'),
            preserve_default=False,
        ),
    ]
