# Generated by Django 5.0.6 on 2024-06-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_idproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(max_length=100, null=True, verbose_name='Categoria del producto'),
        ),
        migrations.AlterField(
            model_name='products',
            name='idproduct',
            field=models.IntegerField(verbose_name='Codigo del producto'),
        ),
    ]
