# Generated by Django 5.0.7 on 2024-08-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_is_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['categories'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
